### ISSUE TITLE
load_survey doesn't return data due to duplicate question check

### ISSUE THREAD

**Issue by lwasser** [earthlab/qtoolkit#10]
Currently the check duplicate questions test is causing the entire function to fail. thus it doesn't return a design object. this should be a warning - not an stop element
```
 Error in grouped_df_impl(data, unname(vars), drop) : 
  Column `question_num` is unknown 
```

**Comment by 1papaya** [comment]
Per ca815ed099f87978c6cb47b68833641bc8e8ed72, check_duplicate_questions default is to throw a warning not an error
