### ISSUE TITLE
Add info on finding your org_id and api_key to README

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/qtoolkit#15]
It would be useful to point new users to resources to make it easy to identify their `org_id` and `api_key` when logging in. 

Maybe these two pages are worth providing as links?

1. [Base URL and Datacenter IDs](https://api.qualtrics.com/docs/root-url)

- Do we need to be explicit here about which part of the hostname is the org id? I tried to use `cuboulder.qualtrics.com` initially, and got an unsuccessful connection error. After that I tried to use `cuboulder` and that seemed to work. 

2. [Authentication: generating tokens](https://api.qualtrics.com/docs/authentication-1)

- It's worth including a warning for new users to avoid hardcoding their API token into scripts and making these public. If we have a clean way for people to provide tokens without directly hardcoding them, that would be worth explaining as a best practice (but this probably warrants a new issue!). 

New users are going to need to provide credentials first, so we need to be super explicit. If they can't get connected to the API, then we've lost them!

**Comment by lwasser** [comment]
i totally agree!! also i guess the authentication method is changing soon... but this is a very good thing to add to the readme. ANd to a vignette. Thanks @mbjoseph

**Comment by lwasser** [comment]
https://github.com/earthlab/qtoolkit/pull/21

**Comment by lwasser** [comment]
oops... this is live now so i'm closing ! thank you for the suggestion @mbjoseph  :)
