### ISSUE TITLE
get_responses() return options

### ISSUE THREAD

**Issue by lwasser** [earthlab/qtoolkit#3]
hey @1papaya  

Currently if i run this code:
```
student_eval <- get_responses(ea_midterm_design, metadata = TRUE)
```
It returns a "melted" gathered data frame where the metdata are stacked UNLESS i chose melt == FALSE. 
I think we should 

1. have a core function `get_responses()` that returns the survey with the metadata unmelted. Thus melt defaults to `FALSE` unless you set it to `TRUE` and metadata defaults to `TRUE` unless you set it to `false`.
2. Then provide the OPTION to melt or remove the metadata if you want.

**Comment by 1papaya** [comment]
Right on, makes sense. Implemented change in 9b0a577.
