### ISSUE TITLE
get responses - melt = TRUE will melt the metadata into the DF

### ISSUE THREAD

**Issue by lwasser** [earthlab/qtoolkit#8]
Currently when melt is set to `TRUE`, the metadata are gathered in the output data.frame.
We need to add some logic that determined if `metadata == TRUE` and if it's true, grab a vector of metadata column names and then make sure those are not gathered. i think you use `-column_name` as the syntax to do this.

**Comment by 1papaya** [comment]
No longer relevant with new qsurvey object
